### ISSUE TITLE
inventory delete

### ISSUE THREAD

**Issue by Mavhill** [coco5843/ProdigygadgetDiamond-Cosmetic-plugin-for-spigot#13]
When a player in survival uses pg via the 3d menu the chosen item is deleting and not replacing the item that they held in slot#4 of bar.  Also the rocket is deleting and not replacing any worn armor when being replaced by astro gear.

Also: Not sure if its intended: ( could go either way on this although any caused damage makes it no longer just cosmetic.)
1. damage can kill players from fall after rocket burns out.
2. damage from meteors is killing players.
3. damage from party poppers and bomb poppers.
4. clones can push players.

**Comment by corentingosselin** [comment]
the chosen item is deleting and not replacing the item that they held in slot#4
You can configure this, check core.yml, or gadget.yml do not remember

2. wtf ? 
3. WTF ?

**Comment by corentingosselin** [comment]
Can't fix damage issues.
Why  ? Could be a source of glitch with survival server with invincible players
