### ISSUE TITLE
Permission typos

### ISSUE THREAD

**Issue by rickylegada** [coco5843/ProdigygadgetDiamond-Cosmetic-plugin-for-spigot#23]
http://truben.no/table/#

The table for your permissions are wrong for the mood cosmetic in which caused me to wonder what am i doing wrong lmao

prodigy.moods.* --> this should be prodigy.mood.*
no 's'
prodigy.mood.surprise --> this should be prodigy.mood.surprised

I think you are missing permissions for gift and cry

Not sure if this typos/permission stuff are qualified to be an issue :D

**Comment by corentingosselin** [comment]
fixed
