### ISSUE TITLE
Music cancel tp issues

### ISSUE THREAD

**Issue by Mavhill** [coco5843/ProdigygadgetDiamond-Cosmetic-plugin-for-spigot#6]
[error for prodigygadgets.txt](https://github.com/coco5843/ProdigyGadget-Advanced-Cosmetic-Hub-Plugin/files/2116830/error.for.prodigygadgets.txt)
When canceling the music playing in dj and then trying to pick new song it will not allow you to without closing and reopening the menu. 
gives message to wait a few seconds before trying but regardless of wait time it will not always allow a new song to be played.

If while using the treasure chest with chests deployed you allow a person to teleport to you it sends errors to the console. 
[https://www.dropbox.com/s/6v4lmy6y4mkom32/error%20for%20prodigygadgets.txt?dl=0](url)

Feature Request: would you please add a random playlist or selected playlist feature to dj.

**Comment by corentingosselin** [comment]
Thank you, will check this one too
