### ISSUE TITLE
error while nothing is running.

### ISSUE THREAD

**Issue by Mavhill** [coco5843/ProdigygadgetDiamond-Cosmetic-plugin-for-spigot#7]
Keep getting this occasionally while nothing is running except 2 idle dj stations. Think tick issue is due to server save which drags ticks under 17.  Also occasionally on restart Dj's break. When going to click to use you end up holding their inventory and having to destroy and reset dj station to make it work again.

[https://www.dropbox.com/s/yutm7um9utddu9m/prodigygadgets%20error.txt?dl=0](url)

**Comment by corentingosselin** [comment]
Thank you for your report,
I am going to check this right now
